### ISSUE TITLE
クレジットとか住所関連の登録情報を変える

### ISSUE THREAD

**Issue by geta6** [geta6/orenoie#7]
- [ ] クレカ
- [ ] 銀行
- [ ] 免許

**Comment by RooandQoo** [comment]
- [ ] クレカ
- [ ] 銀行
- [ ] 免許
-

**Comment by catatsuy** [comment]
住民票は明治通りの交差点のところに区役所出張所があるのでそこでやれば昼休みにできる

**Comment by geta6** [comment]
住民票は移さないことにした
